### ISSUE TITLE
Add the ability to parse more ID3 tags

### ISSUE THREAD

**Issue by jerodsanto** [lawik/id3vx#26]
No need for this to be comprehensive (contributions are indeed welcome!), but rudimentary support would allow us to `replace_tag` our current mp3s that have been written by ffmpeg.

**Comment by jerodsanto** [comment]
I think we need the ability to parse ID3v1 tags as well, if for no other reason then to `replace_tag` them as well. 

In other words: given an arbitrary mp3 that may have any of the following states:

1. Doesn't have an ID3 tag
2. Has an ID3v1 tag
3. Has an ID3v2.X tag
4. Has both ID3v1 tag and ID3v2.X tag (I believe this is possible, but not sure)

We want to be able to call either `replace_tag` on the file _or_ somehow determine where the ID3 header data stops and the mp3 audio data begins so we can reliably build up a `Id3vx.Tag` and `<>` on to the audio data to create a new file.

**Comment by lawik** [comment]
I think a first stab could be `strip_tags` which would just remove any of those tags found.

Is ID3v1 a current need or a maybe? They are found at the back of the file and so are a bit annoying :)

**Comment by jerodsanto** [comment]
As long as we can safely write the new tags, then we’re good. 

-Jerod
(sent on the go)

**Comment by lawik** [comment]
We can safely ignore ID3v1 because those tags live at the end of the file.

So we should be able to implement stripping out ID3v2.4 very easily and ignore ID3v1 as they can co-exist peacefully with other tags.

**Comment by jerodsanto** [comment]
Fair enough 👍

**Comment by lawik** [comment]
Ended up making replace_tag capable of swallowing ID3v2.2 and 2.4 for simple replacing-purposes. Should work for your case I think.

**Comment by lawik** [comment]
New rc2 is up on hex.
