### ISSUE TITLE
Chapters not parseable by ffmpeg

### ISSUE THREAD

**Issue by jerodsanto** [lawik/id3vx#33]
(In my testing so far `ffmpeg` is the closest approximation to "this will work in podcast apps")

The simplest way I've come up with to reproduce this is to add a test to `id3vx_test.exs` that looks like this:

```elixir
test "Replace chapters in atp483.mp3" do
  path = Path.join(@samples_path, "atp483.mp3")
  outpath = "/tmp/out-atp483.mp3"

  # Before:
  {result, _} = System.shell("ffmpeg -i #{path} 2>&1 | grep \"Chapter \" | wc -l")
  chapter_count = result |> String.trim() |> String.to_integer()

  assert chapter_count == 18

  new_tag = Id3vx.Tag.create(3)
  new_tag = Id3vx.Tag.add_typical_chapter_and_toc(new_tag, 0, 60_000, 0, 0, "First Chapter", fn(chapter) -> chapter end)
  
  Id3vx.replace_tag(new_tag, path, outpath)
  
  # After:
  {result, _} = System.shell("ffmpeg -i #{outpath} 2>&1 | grep \"Chapter \" | wc -l")
  chapter_count = result |> String.trim() |> String.to_integer()

  assert chapter_count == 1
end
```

The first assertion passes, because the file has 18 chapters and `ffmpeg -i atp483.mp3` parses them and lists them out. (The rest of that shell pipeline is getting the actual count from ffmpeg's printed output.)

The second assertion fails, because after replacing the chapters with our own using `add_typical_chapter_and_toc`, ffmpeg can no longer parse the chapters, and it returns 0 for the count.

A few things worth noting:

- I'm setting the start/end offsets to 0 because the spec says that's how you indicate you want to use the start/end times
- It also fails if you add sub-frames inside the chapter callback
- If you add a text frame before the chapter frames (such as a title), that data is picked up by ffmpeg

**Comment by lawik** [comment]
Should be solved by 0.0.1-rc4, please check and close if 👍🏻
