### ISSUE TITLE
Pictures not parseable by ffmpeg

### ISSUE THREAD

**Issue by jerodsanto** [lawik/id3vx#34]
(In my testing so far `ffmpeg` is the closest approximation to "this will work in podcast apps")

The simplest way I've come up with to reproduce this is to add a test to `id3vx_test.exs` that looks like this:

```elixir
test "ffmpeg parses attached picture" do
  path = Path.join(@samples_path, "atp483.mp3")
  outpath = "/tmp/out-atp483.mp3"

  # Before:
  {result, _} = System.shell("ffmpeg -i #{path} 2>&1")
  refute String.contains?(result, "Error decoding attached picture description")

  image = File.read!("test/samples/sample.png")
  new_tag = Id3vx.Tag.create(3)
  new_tag = Id3vx.Tag.add_text_frame(new_tag, "TIT2", "Cool Title")
  new_tag = Id3vx.Tag.add_attached_picture(new_tag, "", "image/png", image)
  Id3vx.replace_tag(new_tag, path, outpath)

  # After:
  {result, _} = System.shell("ffmpeg -i #{outpath} 2>&1")
  refute String.contains?(result, "Error decoding attached picture description")
end
```

The first assertion passes because the attached pic in the original atp483.mp3 parses no problem. You can see its details in ffmpeg's output, if that's interesting to you:

```
Stream #0:1: Video: png, rgb24(pc), 3000x3000, 90k tbr, 90k tbn (attached pic)
```

The second assertion fails because when we run it against the pic attached in `new_tag` it raises an error. The exact error that ffmpeg reports back is: 

```
Incorrect BOM value
Error decoding attached picture description.
```

**Comment by lawik** [comment]
Should be solved by 0.0.1-rc4, please check and close if 👍🏻
